name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure and Build (CMake and Make)
      run: |
        mkdir build 
        cd build 
        cmake ..
        cmake --build . 


